# Generated by Django 4.2.18 on 2025-03-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visiteur', '0001_initial'),
        ('directeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_visite', models.DateField()),
                ('heure_visite', models.TimeField()),
                ('objet', models.TextField()),
                ('statut', models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé')], default='confirmé', max_length=20)),
                ('directeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directeur.directeur')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiteur.visiteur')),
            ],
        ),
    ]
