# Generated by Django 4.2.20 on 2025-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='motif_annulation',
            field=models.CharField(blank=True, choices=[('indisponible_directeur', 'Indisponibilité du directeur'), ('ajourné_visiteur', 'Ajournement du visiteur')], max_length=50, null=True),
        ),
    ]
