# Generated by Django 4.2.18 on 2025-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=50)),
                ('type_visiteur', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=40, unique=True)),
            ],
        ),
    ]
