# Generated by Django 3.2.20 on 2025-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaire',
            options={},
        ),
        migrations.AlterModelManagers(
            name='secretaire',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='secretaire',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='secretaire',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
