# Generated by Django 4.2.20 on 2025-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directeur',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=20),
        ),
    ]
