# Generated by Django 4.2.18 on 2025-03-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('validé', 'Validé')], default='en attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
