# Generated by Django 4.2.20 on 2025-03-22 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secretaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('validé', 'Validé')], default='en attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaire.secretaire')),
            ],
        ),
    ]
