# Generated by Django 4.2.18 on 2025-03-02 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programme_visite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmevisite',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
