# Generated by Django 4.2.18 on 2025-03-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programme_visite', '0002_initial'),
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmevisite',
            name='visite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visite.visite'),
        ),
    ]
