# Generated by Django 3.2.20 on 2025-03-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretaire', '0002_auto_20250308_0731'),
        ('programme_visite', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmevisite',
            name='secretaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaire.secretaire'),
        ),
    ]
